networks:
  space_medication_management:
    name: medication_management_space
    driver: bridge

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - space_medication_management
    depends_on:
      - redis
  redis:
    image: "redis:6.2-alpine"
    restart: always
    env_file: .env
    ports:
      - "6388:6379"
    volumes:
      - redis_data:/data
    networks:
      - space_medication_management

volumes:
  pg_data:
  redis_data:
