version: '3.8'

networks:
  space:
    name: medication-management_space
    driver: bridge

services:
  bot:
    container_name: bot_app
    build: ./
    env_file: .env
    networks:
      - space
    depends_on:
      - db
  db:
    image: "postgres:16"
    container_name: bot_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PORT: ${PG_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - space
  celery:
    image: "celery"
    env_file: .env
    command: celery worker --loglevel=info
    depends_on:
      - bot
      - redis
      - db
    networks:
      - space
  redis:
    image: "redis:6.2-alpine"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - space

volumes:
  pg_data:
