version: '3.8'

networks:
  space_medication_management:
    name: medication_management_space
    driver: bridge

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - space_medication_management
    depends_on:
      - db
      - redis
  db:
    image: "postgres:16"
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER_NAME}
      POSTGRES_PORT: ${PG_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - space_medication_management
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: celery -A src.celery_tasks.tasks worker --loglevel=info
    depends_on:
      - bot
      - redis
    networks:
      - space_medication_management
  redis:
    image: "redis:6.2-alpine"
    restart: always
    env_file: .env
    volumes:
      - redis_data:/data
    networks:
      - space_medication_management

volumes:
  pg_data:
  redis_data:
