services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_container
    networks:
      - scheduler_space
    depends_on:
      - redis
  redis:
    image: "redis:6.2-alpine"
    restart: always
    env_file: .env_container
    ports:
      - "6388:6379"
    volumes:
      - redis_data:/data
    networks:
      - scheduler_space

volumes:
  pg_data:
  redis_data:

networks:
  scheduler_space:
    external: true
